export enum ExchangeType {
  CRYPTO_TO_FIAT = 'CRYPTO_TO_FIAT',
  FIAT_TO_CRYPTO = 'FIAT_TO_CRYPTO',
}

export enum TransactionStatus {
  PENDING_OFFER = 'PENDING_OFFER',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_SENT = 'PAYMENT_SENT',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DECLINED = 'DECLINED',
  DISPUTED = 'DISPUTED',
  FINISHED = 'FINISHED',
}

export enum OfferStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
}

export enum RespondAction {
  ACCEPT = 'ACCEPT',
  DECLINE = 'DECLINE',
}

export enum Role {
  CUSTOMER = 'CUSTOMER',
  EXCHANGER = 'EXCHANGER',
  MODERATOR = 'MODERATOR',
} 